name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : login to docker
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag viralvariance/dockerize-php-sample:latest
    - name: Push Docker image 
      run: docker push viralvariance/dockerize-php-sample:latest
